# top level stuff you probably don't need to touch
highlighter: rouge
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://anthonygarvan.github.io/
baseurl: http://anthonygarvan.github.io/
title: Anthony Garvan
author: Anthony Garvan
description: Full Stack Developer
avatar: profile.jpg
email: anthony.garvan@gmail.com
github: anthonygarvan # username
twitter: anthonygarvan
linkedin: anthonygarvan
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-38185442-3


# needed for travis-ci build
exclude: [vendor]
